import { create } from 'zustand'
import { persist } from 'zustand/middleware'

export type Language = 'zh' | 'en'

export interface LanguageState {
  currentLanguage: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

// Translation dictionary
const translations = {
  zh: {
    // Header and Navigation
    'app.title': 'AI 手相算命',
    'app.subtitle': '傳統中式手相解讀',
    'nav.home': '首頁',
    'nav.about': '關於我們',
    'nav.faq': '常見問題',
    'nav.privacy': '隱私政策',
    'language.switch': '切換語言',
    
    // Main Content
    'hero.title': 'AI 智能手相分析',
    'hero.subtitle': '傳統中式手相解讀，揭示你的人生密碼',
    'hero.description': '運用先進的電腦視覺技術和人工智慧算法，精準識別您的生命線、智慧線、感情線等主要掌紋特徵。提供專業的愛情運勢、事業發展、健康狀況分析，讓您深入了解自己的性格特質與未來趨勢。',
    'hero.cta': '開始分析',
    'hero.demo': '查看示例',
    
    // Upload Section
    'upload.title': '上傳手掌照片',
    'upload.subtitle': '清晰的照片能獲得更準確的分析',
    'upload.drag': '拖拽圖片到此處，或點擊選擇文件',
    'upload.camera': '使用相機拍攝',
    'upload.open_camera': '開啟相機',
    'upload.select_file': '選擇檔案',
    'upload.formats': '支持 JPG、PNG 格式',
    'upload.tips': '拍攝建議：充足光線、手掌朝上、距離適中',
    'upload.tip1': '確保手掌清晰可見，手心朝上',
    'upload.tip2': '使用充足的自然光拍攝',
    'upload.tip3': '手掌應佔據畫面的大部分區域',
    
    // Analysis Results
    'analysis.title': '您的手相分析結果',
    'analysis.confidence': '置信度',
    'analysis.warnings': '品質提醒',
    'analysis.topics.emotion': '感情運勢',
    'analysis.topics.intelligence': '智慧學習',
    'analysis.topics.career': '事業發展',
    'analysis.topics.energy': '健康活力',
    
    // Share
    'share.title': '分享您的手相分析',
    'share.description': '與朋友分享您的手相解讀結果',
    'share.facebook': '分享到 Facebook',
    'share.twitter': '分享到 Twitter',
    'share.line': '分享到 LINE',
    'share.whatsapp': '分享到 WhatsApp',
    'share.copy': '複製連結',
    'share.download': '下載圖片',
    'share.copied': '連結已複製',
    'share.downloaded': '圖片已下載',
    'share.copied_clipboard': '已複製到剪貼簿',
    'share.copied_description': '分享連結已複製，可以貼到任何地方分享！',
    'share.copy_failed': '複製失敗',
    'share.copy_failed_description': '請手動複製分享內容',
    'share.share_success': '分享成功',
    'share.shared_via': '已透過',
    'share.download_success': '下載成功',
    'share.download_success_description': '手相分析結果已儲存到你的裝置',
    'share.download_failed': '下載失敗',
    'share.download_failed_description': '無法生成分析結果圖片',
    'share.download_button': '下載',
    'share.share_button': '分享',
    'share.preview': '分享預覽:',
    
    // Features
    'features.title': '功能特色',
    'features.ai.title': 'AI 智能分析',
    'features.ai.description': '先進的計算機視覺技術，精確識別手部特徵',
    'features.traditional.title': '傳統手相學',
    'features.traditional.description': '結合千年中式手相學經驗，提供專業解讀',
    'features.private.title': '隱私保護',
    'features.private.description': '所有分析在本地進行，絕不保存您的照片',
    'features.instant.title': '即時結果',
    'features.instant.description': '幾秒內獲得詳細的手相分析報告',
    
    // FAQ
    'faq.title': '常見問題',
    'faq.accurate.q': '手相分析準確嗎？',
    'faq.accurate.a': '本服務僅供娛樂參考，不應作為人生決策的依據。手相學屬於傳統文化，缺乏科學驗證。',
    'faq.privacy.q': '我的照片會被保存嗎？',
    'faq.privacy.a': '不會。所有分析都在您的設備本地進行，我們不會收集或保存任何個人照片。',
    'faq.quality.q': '如何獲得最佳分析效果？',
    'faq.quality.a': '建議在充足自然光下拍攝，保持手掌平整朝上，距離適中，避免陰影遮擋。',
    'faq.both.q': '需要拍攝雙手嗎？',
    'faq.both.a': '單手即可完成分析。傳統上左手代表先天，右手代表後天，您可以選擇想要分析的手。',
    
    // Footer
    'footer.about': '關於我們',
    'footer.privacy': '隱私政策',
    'footer.terms': '使用條款',
    'footer.contact': '聯繫我們',
    'footer.copyright': '© 2025 掌相解讀AI. 免費線上手相算命工具 - 僅供娛樂參考，請勿迷信',
    'footer.disclaimer': '本服務僅供娛樂，不提供醫療、法律或投資建議。',
    
    // Footer sections
    'footer.tools.title': '手相算命工具',
    'footer.tools.free_analysis': '免費AI手相分析',
    'footer.tools.online_reading': '線上掌相解讀',
    'footer.tools.fortune_telling': '手相占卜預測',
    'footer.tools.palm_recognition': '掌紋特徵識別',
    
    'footer.fortune.title': '運勢解讀',
    'footer.fortune.love': '愛情運勢分析',
    'footer.fortune.career': '事業發展預測',
    'footer.fortune.health': '健康狀況解讀',
    'footer.fortune.personality': '性格特質分析',
    
    'footer.knowledge.title': '掌紋知識',
    'footer.knowledge.lifeline': '生命線解讀指南',
    'footer.knowledge.wisdom': '智慧線分析技巧',
    'footer.knowledge.heart': '感情線占卜方法',
    'footer.knowledge.career_line': '事業線預測解析',
    
    'footer.about_us.title': '關於我們',
    'footer.about_us.technology': 'AI技術說明',
    'footer.about_us.privacy': '隱私政策',
    'footer.about_us.terms': '使用條款',
    'footer.about_us.contact': '聯絡我們',
    
    // Disclaimer
    'disclaimer.title': '使用條款與免責聲明',
    'disclaimer.subtitle': '請仔細閱讀以下條款，了解本服務的性質與限制',
    'disclaimer.main_warning': '重要提醒：本服務僅供娛樂參考，不構成任何形式的專業建議',
    'disclaimer.entertainment': '本服務僅供娛樂參考',
    'disclaimer.not_medical': '不提供任何醫療、法律、投資建議',
    'disclaimer.no_guarantee': '不保證預測準確性',
    'disclaimer.privacy': '您的照片僅在本地處理，不會上傳',
    'disclaimer.accept': '我了解並同意（僅供娛樂參考）',
    'disclaimer.decline': '不同意',
    'disclaimer.service_nature': '服務性質',
    'disclaimer.disclaimers': '免責聲明',
    'disclaimer.privacy_protection': '隱私保護',
    'disclaimer.accuracy': '準確性說明',
    'disclaimer.restrictions': '使用限制',
    'disclaimer.final_notice': '點擊「我了解並同意」表示您已閱讀並理解上述條款，同意將本服務僅用於娛樂目的，並不會將分析結果作為重要決策的依據。',
    
    // Buttons and Actions
    'button.analyze': '開始分析',
    'button.retry': '重新分析',
    'button.back': '返回',
    'button.close': '關閉',
    'button.save': '保存',
    'button.cancel': '取消',
    
    // Status Messages
    'status.uploading': '上傳中...',
    'status.analyzing': '分析中...',
    'status.processing': '處理中...',
    'status.complete': '分析完成',
    'status.error': '分析失敗，請重試',
    
    // Analytics Dashboard (Hidden)
    'analytics.title': '使用統計面板',
    'analytics.sessions': '訪問統計',
    'analytics.sharing': '分享統計',
    'analytics.engagement': '參與度統計',
    'analytics.export': '導出數據',
    'analytics.close': '關閉面板',
    
    // Feedback System
    'feedback.title': '用戶真實評價',
    'feedback.subtitle': '來自全球用戶的真實體驗分享，見證AI手相分析的準確性與專業性',
    'feedback.users': '位用戶',
    'feedback.verified': '已驗證',
    'feedback.totalReviews': '總評價',
    'feedback.averageRating': '平均評分',
    'feedback.satisfaction': '滿意度',
    'feedback.recommend': '推薦率',
    'feedback.ratingDistribution': '評分分布',
    'feedback.verifiedUser': '已驗證',
    'feedback.helpful': '有幫助',
    'feedback.shareExperience': '分享你的體驗',
    'feedback.shareDescription': '你的真實評價將幫助更多人了解我們的服務品質',
    'feedback.writeReview': '撰寫評價',
    'feedback.category.accuracy': '準確性',
    'feedback.category.experience': '使用體驗',
    'feedback.category.design': '界面設計',
    'feedback.category.overall': '整體評價',
    'feedback.form.name': '姓名',
    'feedback.form.namePlaceholder': '請輸入您的姓名',
    'feedback.form.location': '所在地',
    'feedback.form.locationPlaceholder': '如：台北, 台灣',
    'feedback.form.rating': '評分',
    'feedback.form.category': '評價類別',
    'feedback.form.categoryPlaceholder': '請選擇評價類別',
    'feedback.form.comment': '評價內容',
    'feedback.form.commentPlaceholder': '分享您的使用體驗和感受...',
    'feedback.form.characters': '字符',
    'feedback.form.minimum': '字符最少',
    'feedback.stars': '星',
    'feedback.error': '錯誤',
    'feedback.fillAllFields': '請填寫所有必填欄位',
    'feedback.commentTooShort': '評價內容至少需要20個字符',
    'feedback.success': '提交成功',
    'feedback.thankYou': '感謝您的寶貴意見！',
    'feedback.submit': '提交評價',
    'feedback.privacy': '您的評價將在審核後公開顯示，我們重視您的隱私保護',
    
    // Filters
    'filters.title': '圖像濾鏡',
    'filters.presets': '預設濾鏡',
    'filters.basic': '基本調整',
    'filters.color': '色彩調整',
    'filters.effects': '特效',
    'filters.brightness': '亮度',
    'filters.contrast': '對比度',
    'filters.saturation': '飽和度',
    'filters.sharpness': '銳化',
    'filters.temperature': '色溫',
    'filters.tint': '色調',
    'filters.sepia': '復古',
    'filters.blur': '模糊',
    'filters.vintage': '懷舊',
    'filters.vignette': '暈影',
    'filters.reset': '重置',
    'filters.download': '下載',
    'filters.apply': '應用濾鏡',
    'filters.none': '無',
    'filters.presets.natural': '自然',
    'filters.presets.enhanced': '增強',
    'filters.presets.dramatic': '戲劇化',
    'filters.presets.vintage': '復古',
    'filters.presets.professional': '專業',
    'filters.presets.mystical': '神秘',
    
    // Detection
    'detection.success': '手部檢測成功',
    'detection.successDesc': '已識別到手部關鍵點，可以開始分析',
    'detection.failed': '未能檢測到清晰的手部，請嘗試重新拍攝',
    'detection.error': '圖片處理失敗，請稍後再試',
    'detection.analyzing': '分析中...',
    'detection.landmarksDetected': '已檢測到手部關鍵點',
    'detection.handOrientation': '手部方向',
    'detection.rightHand': '右手',
    'detection.leftHand': '左手',
    'detection.readyForAnalysis': '準備進行掌相分析',
    
    // 批量處理
    'batch.title': '批量處理',
    'batch.subtitle': '一次處理多張掌相圖片',
    'batch.uploadTitle': '上傳多張圖片',
    'batch.uploadSubtitle': '拖拽多張手掌照片到此處或點擊選擇文件',
    'batch.selectFiles': '選擇文件',
    'batch.globalSettings': '全域設定',
    'batch.applyGlobalFilters': '對所有圖片應用全域濾鏡',
    'batch.preset': '濾鏡預設',
    'batch.images': '張圖片',
    'batch.processing': '處理中',
    'batch.completed': '已完成',
    'batch.processed': '已處理',
    'batch.analyzed': '已分析',
    'batch.startProcessing': '開始處理',
    'batch.stopProcessing': '停止處理',
    'batch.exportAll': '導出全部',
    'batch.clearAll': '清空全部',
    'batch.download': '下載',
    'batch.progress': '進度',
    'batch.imageList': '圖片列表',

    // Theme
    'theme.light': '浅色模式',
    'theme.dark': '深色模式',
    'theme.system': '跟随系统',
    'theme.toggle': '切换主题',

    // Onboarding
    'onboarding.welcome.title': '歡迎使用 AI 手相分析',
    'onboarding.welcome.description': '讓我們為您介紹這個強大的掌相解讀平台的所有功能特色',
    'onboarding.welcome.footer': '您可以隨時在設定中重新開始導覽',
    'onboarding.step': '步驟',
    'onboarding.of': '／',
    'onboarding.next': '下一步',
    'onboarding.previous': '上一步',
    'onboarding.skip_tour': '跳過導覽',
    'onboarding.complete': '完成導覽',
    'onboarding.start_tour': '開始導覽',
    'onboarding.skip_explore': '跳過並探索',
    'onboarding.auto_advance': '自動前進',
    'onboarding.pause_auto': '暫停自動',
    'onboarding.try_now': '立即嘗試：',
    'onboarding.available_filters': '可用濾鏡：',
    'onboarding.customize_experience': '自訂體驗設定',
    'onboarding.language': '介面語言',
    'onboarding.language_desc': '選擇您偏好的介面語言',
    'onboarding.theme': '外觀主題',
    'onboarding.theme_desc': '選擇淺色或深色主題',
    'onboarding.show_hints': '顯示提示',
    'onboarding.skip_animations': '跳過動畫',
    'onboarding.setup.beginner': '新手模式',
    'onboarding.setup.beginner_desc': '自動導覽，包含所有提示和說明',
    'onboarding.setup.advanced': '進階模式',
    'onboarding.setup.advanced_desc': '手動控制，詳細功能介紹',
    'onboarding.setup.minimal': '精簡模式',
    'onboarding.setup.minimal_desc': '快速導覽，減少動畫效果',
    'onboarding.features.palm_analysis': 'AI 手相分析',
    'onboarding.features.palm_analysis_desc': '精準識別掌紋特徵，提供個人化解讀',
    'onboarding.features.image_filters': '專業影像濾鏡',
    'onboarding.features.image_filters_desc': '多種濾鏡選項優化照片品質',
    'onboarding.features.batch_processing': '批量處理',
    'onboarding.features.batch_processing_desc': '一次處理多張照片，提高效率',
    'onboarding.features.themes': '主題切換',
    'onboarding.features.themes_desc': '淺色／深色模式自由切換',
    'onboarding.features.analytics': '使用分析',
    'onboarding.features.analytics_desc': '詳細的使用統計和見解分析',
    'onboarding.features.social_sharing': '社群分享',
    'onboarding.features.social_sharing_desc': '輕鬆分享結果到各大社交平台',
    'onboarding.steps.welcome.title': '歡迎使用 AI 手相分析',
    'onboarding.steps.welcome.description': '探索古老智慧與現代科技的完美結合，開始您的掌相解讀之旅。',
    'onboarding.steps.theme-intro.title': '選擇您的完美主題',
    'onboarding.steps.theme-intro.description': '在淺色和深色模式之間切換，或讓應用程式自動跟隨您的系統偏好設定。',
    'onboarding.steps.upload-photo.title': '上傳您的手掌照片',
    'onboarding.steps.upload-photo.description': '拍攝清晰的手掌照片或從相簿中選擇。良好的光線能確保更準確的分析結果。',
    'onboarding.steps.image-filters.title': '增強您的影像',
    'onboarding.steps.image-filters.description': '使用專業濾鏡改善影像品質。嘗試預設選項或手動調整以獲得最佳效果。',
    'onboarding.steps.palm-analysis.title': '獲得您的解讀',
    'onboarding.steps.palm-analysis.description': '我們的 AI 會分析您的掌紋，提供關於情感、智慧、事業和活力的深度見解。',
    'onboarding.steps.batch-processing.title': '處理多張影像',
    'onboarding.steps.batch-processing.description': '使用批量處理功能一次分析多張手掌照片，並套用一致的濾鏡設定。',
    'onboarding.steps.social-sharing.title': '分享您的結果',
    'onboarding.steps.social-sharing.description': '將手相解讀結果分享到社交媒體，或下載保存以供日後參考。',
    'onboarding.steps.analytics-dashboard.title': '追蹤您的旅程',
    'onboarding.steps.analytics-dashboard.description': '點擊標誌 5 次即可存取詳細分析，查看您的使用模式和深度見解。',

    // Common
    'common.cancel': '取消',
    'header.badges.rating': '4.8分',
    'header.badges.users': '已服務2847+用戶',
    'disclaimer.notice': '重要聲明：',
    'upload.title_with_action': '上傳手掌照片開始算命',
    'upload.description': '請上傳清晰的<strong>手掌照片</strong>，我們的AI系統將自動識別<strong>掌紋特徵</strong>並進行<strong>手相分析</strong>',
    'batch.mode': '批量模式',
    'instructions.title': '手相拍攝技巧指南',
    'instructions.item1.title': '光線充足環境',
    'instructions.item1.description': '使用自然光或明亮的室內照明，確保<strong>掌紋清晰可見</strong>',
    'instructions.item2.title': '手心朝上姿勢',
    'instructions.item2.description': '確保<strong>生命線、智慧線、感情線</strong>等主要掌紋完整呈現',
    'instructions.item3.title': '手掌填滿畫面',
    'instructions.item3.description': '手掌佔據照片大部分區域，提高<strong>AI識別準確度</strong>',
    'instructions.item4.title': '避免模糊晃動',
    'instructions.item4.description': '保持手部穩定，確保<strong>掌紋細節</strong>清晰可辨',
    'knowledge.title': '手相算命基礎知識 - 掌紋解讀入門',
    'knowledge.description': '了解主要<strong>掌紋線條</strong>的含義，掌握<strong>手相占卜</strong>的基本原理',
    'knowledge.lifeline.title': '生命線解讀',
    'knowledge.lifeline.description': '圍繞<strong>拇指球</strong>的弧線，反映個人的<strong>體力、健康狀況</strong>和<strong>生活穩定性</strong>。線條深長代表體質強健，斷裂則可能預示生活變動期。',
    'knowledge.wisdomline.title': '智慧線分析',
    'knowledge.wisdomline.description': '橫向穿過手掌的線條，象徵<strong>思維能力、學習天賦</strong>和<strong>理性判斷力</strong>。長直的智慧線顯示邏輯思維強，彎曲則表示富有創意和感性。',
    'knowledge.loveline.title': '感情線占卜',
    'knowledge.loveline.description': '手掌上方的橫線，代表<strong>愛情運勢、情感表達</strong>和<strong>人際關係</strong>。線條深刻表示感情豐富，斷續則可能有情感波動或多段感情。',
    'knowledge.careerline.title': '事業線預測',
    'knowledge.careerline.description': '從手掌底部向上延伸的線條，反映<strong>職業發展、事業成就</strong>和<strong>人生目標</strong>。明顯的事業線表示目標明確，斷裂或偏移可能預示職涯轉換。',
    'features.section_title': 'AI手相算命功能特色',
    'features.item1.title': 'AI智能識別技術',
    'features.item1.description': '採用先進的<strong>機器學習算法</strong>和<strong>電腦視覺技術</strong>，精準識別21個手部關鍵點，自動分析<strong>掌紋走向、深淺、斷裂</strong>等細節特徵。',
    'features.item2.title': '全方位運勢解讀',
    'features.item2.description': '提供<strong>愛情、事業、健康、智慧</strong>四大面向的詳細分析，結合傳統手相學原理，給出個人化的<strong>性格特質</strong>和<strong>未來趨勢預測</strong>。',
    'features.item3.title': '免費即時分析',
    'features.item3.description': '完全<strong>免費使用</strong>，無需註冊登入，上傳照片後即可獲得專業的<strong>手相解讀報告</strong>，包含信心指數和詳細說明，讓您快速了解自己的掌相密碼。',
    'faq.section_title': '手相算命常見問題',
    'faq.section_description': '關於線上手相占卜的常見疑問解答',
    'faq.item1.question': 'AI手相算命準確嗎？',
    'faq.item1.answer': '我們的AI系統基於大量手相數據訓練，能識別主要掌紋特徵並給出參考性分析。但請記住，<strong>手相占卜僅供娛樂參考</strong>，不應作為重大決策的依據。',
    'faq.item2.question': '如何拍攝出最佳的手相照片？',
    'faq.item2.answer': '建議在自然光下拍攝，<strong>手心朝上</strong>，確保<strong>掌紋清晰</strong>。避免陰影遮擋，讓手掌佔據照片主要區域。良好的照片品質能提高AI分析的準確度。',
    'faq.item3.question': '左手還是右手比較準？',
    'faq.item3.answer': '傳統手相學認為<strong>右手代表後天發展</strong>，<strong>左手代表天生特質</strong>。建議拍攝慣用手（大多數人的右手），這樣能更好反映個人的性格發展軌跡。',
    'analysis.card.title': '手掌特徵分析中',
    'analysis.card.description_landmarks': 'AI已成功檢測到手部關鍵點，準備進行掌相解讀',
    'analysis.card.description_no_landmarks': '正在使用電腦視覺技術分析手部特徵...', 
    'analysis.card.button_reset': '重新上傳照片',
    'analysis.card.button_analyzing': '正在解讀手相...', 
    'analysis.card.button_start': '開始AI算命分析',
    'analysis.wait.title': '等待掌相解讀',
    'analysis.wait.description': '請等待AI完成手部特徵檢測後開始個人化運勢分析',
    'analysis.wait.message': '準備進行專業掌相分析',
    'analysis.wait.submessage': '包含愛情、事業、健康、智慧四大運勢',
    'footer.links.tools.title': '手相算命工具',
    'footer.links.tools.item1': '免費AI手相分析',
    'footer.links.tools.item2': '線上掌相解讀',
    'footer.links.tools.item3': '手相占卜預測',
    'footer.links.tools.item4': '掌紋特徵識別',
    'footer.links.readings.title': '運勢解讀',
    'footer.links.readings.item1': '愛情運勢分析',
    'footer.links.readings.item2': '事業發展預測',
    'footer.links.readings.item3': '健康狀況解讀',
    'footer.links.readings.item4': '性格特質分析',
    'footer.links.knowledge.title': '掌紋知識',
    'footer.links.knowledge.item1': '生命線解讀指南',
    'footer.links.knowledge.item2': '智慧線分析技巧',
    'footer.links.knowledge.item3': '感情線占卜方法',
    'footer.links.knowledge.item4': '事業線預測解析',
    'footer.links.about.title': '關於我們',
    'footer.links.about.item1': 'AI技術說明',
    'footer.links.about.item2': '隱私政策',
    'footer.links.about.item3': '使用條款',
    'footer.links.about.item4': '聯絡我們',
    'footer.copyright_full': '© 2025 掌相解讀AI. 免費線上手相算命工具 - 僅供娛樂參考，請勿迷信',
    'footer.keywords': '關鍵詞：手相算命, AI手相分析, 掌相解讀, 免費算命, 線上占卜, 運勢預測, 愛情運勢, 事業運勢'
  },
  en: {
    // Header and Navigation
    'app.title': 'AI Palm Reading',
    'app.subtitle': 'Traditional Chinese Palmistry',
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.faq': 'FAQ',
    'nav.privacy': 'Privacy Policy',
    'language.switch': 'Switch Language',
    
    // Main Content
    'hero.title': 'AI-Powered Palm Reading',
    'hero.subtitle': 'Traditional Chinese palmistry to reveal your life insights',
    'hero.description': 'Using advanced computer vision technology and AI algorithms to precisely identify your life line, wisdom line, love line and other major palm features. Provides professional analysis of love fortune, career development, and health status to help you understand your personality traits and future trends.',
    'hero.cta': 'Start Analysis',
    'hero.demo': 'View Demo',
    
    // Upload Section
    'upload.title': 'Upload Palm Photo',
    'upload.subtitle': 'Clear photos provide more accurate analysis',
    'upload.drag': 'Drag image here, or click to select file',
    'upload.camera': 'Use Camera',
    'upload.open_camera': 'Open Camera',
    'upload.select_file': 'Select File',
    'upload.formats': 'Supports JPG, PNG formats',
    'upload.tips': 'Photo Tips: Good lighting, palm facing up, appropriate distance',
    'upload.tip1': 'Ensure palm is clearly visible, palm facing up',
    'upload.tip2': 'Use sufficient natural light for photography',
    'upload.tip3': 'Palm should occupy most of the frame area',
    
    // Analysis Results
    'analysis.title': 'Your Palm Reading Results',
    'analysis.confidence': 'Confidence',
    'analysis.warnings': 'Quality Warnings',
    'analysis.topics.emotion': 'Love & Relationships',
    'analysis.topics.intelligence': 'Intelligence & Learning',
    'analysis.topics.career': 'Career Development',
    'analysis.topics.energy': 'Health & Vitality',
    
    // Share
    'share.title': 'Share Your Palm Reading',
    'share.description': 'Share your palm reading results with friends',
    'share.facebook': 'Share on Facebook',
    'share.twitter': 'Share on Twitter',
    'share.line': 'Share on LINE',
    'share.whatsapp': 'Share on WhatsApp',
    'share.copy': 'Copy Link',
    'share.download': 'Download Image',
    'share.copied': 'Link copied',
    'share.downloaded': 'Image downloaded',
    'share.copied_clipboard': 'Copied to Clipboard',
    'share.copied_description': 'Share link has been copied, you can paste it anywhere to share!',
    'share.copy_failed': 'Copy Failed',
    'share.copy_failed_description': 'Please manually copy the share content',
    'share.share_success': 'Share Successful',
    'share.shared_via': 'Shared via',
    'share.download_success': 'Download Successful',
    'share.download_success_description': 'Palm reading result has been saved to your device',
    'share.download_failed': 'Download Failed',
    'share.download_failed_description': 'Unable to generate analysis result image',
    'share.download_button': 'Download',
    'share.share_button': 'Share',
    'share.preview': 'Share Preview:',
    
    // Features
    'features.title': 'Key Features',
    'features.ai.title': 'AI Analysis',
    'features.ai.description': 'Advanced computer vision technology for precise hand feature recognition',
    'features.traditional.title': 'Traditional Palmistry',
    'features.traditional.description': 'Combines thousands of years of Chinese palmistry wisdom for professional insights',
    'features.private.title': 'Privacy Protection',
    'features.private.description': 'All analysis performed locally, your photos are never saved',
    'features.instant.title': 'Instant Results',
    'features.instant.description': 'Get detailed palm reading reports within seconds',
    
    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.accurate.q': 'Is palm reading accurate?',
    'faq.accurate.a': 'This service is for entertainment purposes only and should not be used as a basis for life decisions. Palmistry is a traditional practice that lacks scientific validation.',
    'faq.privacy.q': 'Are my photos saved?',
    'faq.privacy.a': 'No. All analysis is performed locally on your device, and we do not collect or store any personal photos.',
    'faq.quality.q': 'How to get the best analysis results?',
    'faq.quality.a': 'We recommend taking photos in good natural lighting, keeping your palm flat and facing up, at an appropriate distance, avoiding shadows.',
    'faq.both.q': 'Do I need to photograph both hands?',
    'faq.both.a': 'A single hand is sufficient for analysis. Traditionally, the left hand represents innate traits while the right hand represents acquired traits.',
    
    // Footer
    'footer.about': 'About Us',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.contact': 'Contact Us',
    'footer.copyright': '© 2025 AI Palm Reading. Free online palmistry tool - for entertainment only.',
    'footer.disclaimer': 'This service is for entertainment only and does not provide medical, legal, or investment advice.',
    'footer.keywords': 'Keywords: palm reading, AI palm analysis, palmistry, free fortune telling, online divination, fortune prediction, love fortune, career fortune',
    
    // Footer sections
    'footer.tools.title': 'Palm Reading Tools',
    'footer.tools.free_analysis': 'Free AI Palm Analysis',
    'footer.tools.online_reading': 'Online Palm Reading',
    'footer.tools.fortune_telling': 'Palm Fortune Telling',
    'footer.tools.palm_recognition': 'Palm Line Recognition',
    
    'footer.fortune.title': 'Fortune Analysis',
    'footer.fortune.love': 'Love Fortune Analysis',
    'footer.fortune.career': 'Career Development Prediction',
    'footer.fortune.health': 'Health Status Reading',
    'footer.fortune.personality': 'Personality Trait Analysis',
    
    'footer.knowledge.title': 'Palm Line Knowledge',
    'footer.knowledge.lifeline': 'Life Line Reading Guide',
    'footer.knowledge.wisdom': 'Wisdom Line Analysis Tips',
    'footer.knowledge.heart': 'Heart Line Divination Methods',
    'footer.knowledge.career_line': 'Career Line Prediction Analysis',
    
    'footer.about_us.title': 'About Us',
    'footer.about_us.technology': 'AI Technology Description',
    'footer.about_us.privacy': 'Privacy Policy',
    'footer.about_us.terms': 'Terms of Service',
    'footer.about_us.contact': 'Contact Us',
    
    // Footer Links (matching the Chinese structure)
    'footer.links.tools.title': 'Palm Reading Tools',
    'footer.links.tools.item1': 'Free AI Palm Analysis',
    'footer.links.tools.item2': 'Online Palm Reading',
    'footer.links.tools.item3': 'Palm Fortune Telling',
    'footer.links.tools.item4': 'Palm Line Recognition',
    'footer.links.readings.title': 'Fortune Readings',
    'footer.links.readings.item1': 'Love Fortune Analysis',
    'footer.links.readings.item2': 'Career Development Prediction',
    'footer.links.readings.item3': 'Health Status Reading',
    'footer.links.readings.item4': 'Personality Trait Analysis',
    'footer.links.knowledge.title': 'Palmistry Knowledge',
    'footer.links.knowledge.item1': 'Life Line Reading Guide',
    'footer.links.knowledge.item2': 'Wisdom Line Analysis Tips',
    'footer.links.knowledge.item3': 'Heart Line Divination Methods',
    'footer.links.knowledge.item4': 'Career Line Prediction Analysis',
    'footer.links.about.title': 'About Us',
    'footer.links.about.item1': 'AI Technology',
    'footer.links.about.item2': 'Privacy Policy',
    'footer.links.about.item3': 'Terms of Service',
    'footer.links.about.item4': 'Contact Us',
    'footer.copyright_full': '© 2025 AI Palm Reading. Free online palmistry tool - for entertainment only.',
    
    // Common
    'common.cancel': 'Cancel',
    'header.badges.rating': '4.8★',
    'header.badges.users': '2847+ Users Served',
    'disclaimer.notice': 'Important Notice:',
    'upload.title_with_action': 'Upload Palm Photo to Start Reading',
    'upload.description': 'Please upload a clear <strong>palm photo</strong>, our AI system will automatically identify <strong>palm features</strong> and perform <strong>palm analysis</strong>',
    'batch.mode': 'Batch Mode',
    'instructions.title': 'Palm Photography Guide',
    'instructions.item1.title': 'Good Lighting Environment',
    'instructions.item1.description': 'Use natural light or bright indoor lighting to ensure <strong>palm lines are clearly visible</strong>',
    'instructions.item2.title': 'Palm Facing Up Position',
    'instructions.item2.description': 'Ensure <strong>life line, wisdom line, heart line</strong> and other major palm lines are fully displayed',
    'instructions.item3.title': 'Palm Fills the Frame',
    'instructions.item3.description': 'Palm occupies most of the photo area to improve <strong>AI recognition accuracy</strong>',
    'instructions.item4.title': 'Avoid Blur and Shake',
    'instructions.item4.description': 'Keep hand steady to ensure <strong>palm line details</strong> are clear and identifiable',
    'knowledge.title': 'Palm Reading Fundamentals - Introduction to Palmistry',
    'knowledge.description': 'Learn the meaning of major <strong>palm lines</strong> and master the basic principles of <strong>palm divination</strong>',
    'knowledge.lifeline.title': 'Life Line Reading',
    'knowledge.lifeline.description': 'The arc line around the <strong>thumb mound</strong>, reflecting personal <strong>vitality, health condition</strong> and <strong>life stability</strong>. Deep and long lines indicate strong constitution, breaks may indicate periods of life changes.',
    'knowledge.wisdomline.title': 'Wisdom Line Analysis',
    'knowledge.wisdomline.description': 'The line crossing the palm horizontally, symbolizing <strong>thinking ability, learning talent</strong> and <strong>rational judgment</strong>. Long straight wisdom lines show strong logical thinking, curves indicate creativity and sensitivity.',
    'knowledge.loveline.title': 'Heart Line Divination',
    'knowledge.loveline.description': 'The horizontal line at the top of the palm, representing <strong>love fortune, emotional expression</strong> and <strong>interpersonal relationships</strong>. Deep lines indicate rich emotions, breaks may suggest emotional fluctuations or multiple relationships.',
    'knowledge.careerline.title': 'Career Line Prediction',
    'knowledge.careerline.description': 'The line extending upward from the bottom of the palm, reflecting <strong>career development, professional achievements</strong> and <strong>life goals</strong>. Clear career lines indicate clear objectives, breaks or deviations may predict career transitions.',
    'features.section_title': 'AI Palm Reading Features',
    'features.item1.title': 'AI Intelligent Recognition Technology',
    'features.item1.description': 'Uses advanced <strong>machine learning algorithms</strong> and <strong>computer vision technology</strong> to precisely identify 21 hand key points, automatically analyzing <strong>palm line direction, depth, breaks</strong> and other detailed features.',
    'features.item2.title': 'Comprehensive Fortune Reading',
    'features.item2.description': 'Provides detailed analysis of <strong>love, career, health, wisdom</strong> in four major aspects, combining traditional palmistry principles to give personalized <strong>personality traits</strong> and <strong>future trend predictions</strong>.',
    'features.item3.title': 'Free Instant Analysis',
    'features.item3.description': 'Completely <strong>free to use</strong>, no registration required, get professional <strong>palm reading reports</strong> after uploading photos, including confidence scores and detailed explanations to help you quickly understand your palm secrets.',
    'faq.section_title': 'Palm Reading FAQ',
    'faq.section_description': 'Common questions about online palm divination',
    'faq.item1.question': 'Is AI palm reading accurate?',
    'faq.item1.answer': 'Our AI system is trained on extensive palm reading data and can identify major palm features to provide reference analysis. However, please remember that <strong>palm divination is for entertainment only</strong> and should not be used as a basis for major decisions.',
    'faq.item2.question': 'How to take the best palm photos?',
    'faq.item2.answer': 'We recommend taking photos in natural light with <strong>palm facing up</strong>, ensuring <strong>palm lines are clear</strong>. Avoid shadow obstruction and let the palm occupy the main area of the photo. Good photo quality improves AI analysis accuracy.',
    'faq.item3.question': 'Left hand or right hand more accurate?',
    'faq.item3.answer': 'Traditional palmistry believes <strong>right hand represents acquired development</strong> and <strong>left hand represents innate traits</strong>. We recommend photographing your dominant hand (most people\'s right hand) as it better reflects personal character development trajectory.',
    'analysis.card.title': 'Analyzing Palm Features',
    'analysis.card.description_landmarks': 'AI successfully detected hand key points, ready for palm analysis',
    'analysis.card.description_no_landmarks': 'Using computer vision technology to analyze hand features...',
    'analysis.card.button_reset': 'Upload New Photo',
    'analysis.card.button_analyzing': 'Analyzing Palm Lines...',
    'analysis.card.button_start': 'Start AI Fortune Analysis',
    'analysis.wait.title': 'Waiting for Palm Reading',
    'analysis.wait.description': 'Please wait for AI to complete hand feature detection before starting personalized fortune analysis',
    'analysis.wait.message': 'Preparing for professional palm analysis',
    'analysis.wait.submessage': 'Including love, career, health, and wisdom fortune',
    
    // Disclaimer
    'disclaimer.title': 'Terms of Use & Disclaimer',
    'disclaimer.subtitle': 'Please read the following terms carefully to understand the nature and limitations of this service',
    'disclaimer.main_warning': 'Important Notice: This service is for entertainment purposes only and does not constitute any form of professional advice',
    'disclaimer.entertainment': 'This service is for entertainment purposes only',
    'disclaimer.not_medical': 'Does not provide medical, legal, or investment advice',
    'disclaimer.no_guarantee': 'No guarantee of prediction accuracy',
    'disclaimer.privacy': 'Your photos are processed locally only and not uploaded',
    'disclaimer.accept': 'I understand and agree (Entertainment Only)',
    'disclaimer.decline': 'Decline',
    'disclaimer.service_nature': 'Service Nature',
    'disclaimer.disclaimers': 'Disclaimers',
    'disclaimer.privacy_protection': 'Privacy Protection',
    'disclaimer.accuracy': 'Accuracy Statement',
    'disclaimer.restrictions': 'Usage Restrictions',
    'disclaimer.final_notice': 'By clicking "I understand and agree", you acknowledge that you have read and understood the above terms, agree to use this service for entertainment purposes only, and will not use the analysis results as a basis for important decisions.',
    
    // Buttons and Actions
    'button.analyze': 'Start Analysis',
    'button.retry': 'Retry Analysis',
    'button.back': 'Back',
    'button.close': 'Close',
    'button.save': 'Save',
    'button.cancel': 'Cancel',
    
    // Status Messages
    'status.uploading': 'Uploading...',
    'status.analyzing': 'Analyzing...',
    'status.processing': 'Processing...',
    'status.complete': 'Analysis Complete',
    'status.error': 'Analysis failed, please retry',
    
    // Analytics Dashboard (Hidden)
    'analytics.title': 'Analytics Dashboard',
    'analytics.sessions': 'Session Analytics',
    'analytics.sharing': 'Sharing Analytics',
    'analytics.engagement': 'Engagement Analytics',
    'analytics.export': 'Export Data',
    'analytics.close': 'Close Dashboard',
    
    // Feedback System
    'feedback.title': 'User Reviews & Testimonials',
    'feedback.subtitle': 'Real experiences from users worldwide, witnessing the accuracy and professionalism of AI palm reading',
    'feedback.users': 'users',
    'feedback.verified': 'verified',
    'feedback.totalReviews': 'Total Reviews',
    'feedback.averageRating': 'Average Rating',
    'feedback.satisfaction': 'Satisfaction',
    'feedback.recommend': 'Recommend Rate',
    'feedback.ratingDistribution': 'Rating Distribution',
    'feedback.verifiedUser': 'Verified',
    'feedback.helpful': 'Helpful',
    'feedback.shareExperience': 'Share Your Experience',
    'feedback.shareDescription': 'Your honest review will help others understand our service quality',
    'feedback.writeReview': 'Write Review',
    'feedback.category.accuracy': 'Accuracy',
    'feedback.category.experience': 'User Experience',
    'feedback.category.design': 'Interface Design',
    'feedback.category.overall': 'Overall Rating',
    'feedback.form.name': 'Name',
    'feedback.form.namePlaceholder': 'Enter your name',
    'feedback.form.location': 'Location',
    'feedback.form.locationPlaceholder': 'e.g., New York, USA',
    'feedback.form.rating': 'Rating',
    'feedback.form.category': 'Review Category',
    'feedback.form.categoryPlaceholder': 'Select review category',
    'feedback.form.comment': 'Review Content',
    'feedback.form.commentPlaceholder': 'Share your experience and thoughts...',
    'feedback.form.characters': 'characters',
    'feedback.form.minimum': 'minimum required',
    'feedback.stars': 'stars',
    'feedback.error': 'Error',
    'feedback.fillAllFields': 'Please fill in all required fields',
    'feedback.commentTooShort': 'Review content must be at least 20 characters',
    'feedback.success': 'Submitted Successfully',
    'feedback.thankYou': 'Thank you for your valuable feedback!',
    'feedback.submit': 'Submit Review',
    'feedback.privacy': 'Your review will be displayed publicly after moderation. We value your privacy protection.',
    
    // Filters
    'filters.title': 'Image Filters',
    'filters.presets': 'Filter Presets',
    'filters.basic': 'Basic Adjustments',
    'filters.color': 'Color Adjustments',
    'filters.effects': 'Effects',
    'filters.brightness': 'Brightness',
    'filters.contrast': 'Contrast',
    'filters.saturation': 'Saturation',
    'filters.sharpness': 'Sharpness',
    'filters.temperature': 'Temperature',
    'filters.tint': 'Tint',
    'filters.sepia': 'Sepia',
    'filters.blur': 'Blur',
    'filters.vintage': 'Vintage',
    'filters.vignette': 'Vignette',
    'filters.reset': 'Reset',
    'filters.download': 'Download',
    'filters.apply': 'Apply Filters',
    'filters.none': 'None',
    'filters.presets.natural': 'Natural',
    'filters.presets.enhanced': 'Enhanced',
    'filters.presets.dramatic': 'Dramatic',
    'filters.presets.vintage': 'Vintage',
    'filters.presets.professional': 'Professional',
    'filters.presets.mystical': 'Mystical',
    
    // Detection
    'detection.success': 'Hand Detection Successful',
    'detection.successDesc': 'Hand landmarks identified, ready for analysis',
    'detection.failed': 'Unable to detect clear hand, please try taking another photo',
    'detection.error': 'Image processing failed, please try again later',
    'detection.analyzing': 'Analyzing...',
    'detection.landmarksDetected': 'Hand landmarks detected',
    'detection.handOrientation': 'Hand orientation',
    'detection.rightHand': 'Right hand',
    'detection.leftHand': 'Left hand',
    'detection.readyForAnalysis': 'Ready for palm analysis',
    
    // Batch Processing
    'batch.title': 'Batch Processing',
    'batch.subtitle': 'Process multiple palm images at once',
    'batch.uploadTitle': 'Upload Multiple Images',
    'batch.uploadSubtitle': 'Drag and drop multiple hand photos or click to select',
    'batch.selectFiles': 'Select Files',
    'batch.globalSettings': 'Global Settings',
    'batch.applyGlobalFilters': 'Apply global filters to all images',
    'batch.preset': 'Filter Preset',
    'batch.images': 'images',
    'batch.processing': 'Processing',
    'batch.completed': 'completed',
    'batch.processed': 'Processed',
    'batch.analyzed': 'Analyzed',
    'batch.startProcessing': 'Start Processing',
    'batch.stopProcessing': 'Stop Processing',
    'batch.exportAll': 'Export All',
    'batch.clearAll': 'Clear All',
    'batch.download': 'Download',
    'batch.progress': 'Progress',
    'batch.imageList': 'Image List',

    // Theme
    'theme.light': 'Light Mode',
    'theme.dark': 'Dark Mode',
    'theme.system': 'System',
    'theme.toggle': 'Toggle Theme',

    // Onboarding
    'onboarding.welcome.title': 'Welcome to AI Palm Reading',
    'onboarding.welcome.description': 'Let us introduce you to all the powerful features of this advanced palmistry platform',
    'onboarding.welcome.footer': 'You can restart this tour anytime from settings',
    'onboarding.step': 'Step',
    'onboarding.of': 'of',
    'onboarding.next': 'Next',
    'onboarding.previous': 'Previous',
    'onboarding.skip_tour': 'Skip Tour',
    'onboarding.complete': 'Complete Tour',
    'onboarding.start_tour': 'Start Tour',
    'onboarding.skip_explore': 'Skip & Explore',
    'onboarding.auto_advance': 'Auto Advance',
    'onboarding.pause_auto': 'Pause Auto',
    'onboarding.try_now': 'Try now:',
    'onboarding.available_filters': 'Available filters:',
    'onboarding.customize_experience': 'Customize Your Experience',
    'onboarding.language': 'Interface Language',
    'onboarding.language_desc': 'Choose your preferred interface language',
    'onboarding.theme': 'Appearance Theme',
    'onboarding.theme_desc': 'Select light or dark theme',
    'onboarding.show_hints': 'Show Hints',
    'onboarding.skip_animations': 'Skip Animations',
    'onboarding.setup.beginner': 'Beginner',
    'onboarding.setup.beginner_desc': 'Auto-guided tour with all hints and explanations',
    'onboarding.setup.advanced': 'Advanced',
    'onboarding.setup.advanced_desc': 'Manual control with detailed feature introduction',
    'onboarding.setup.minimal': 'Minimal',
    'onboarding.setup.minimal_desc': 'Quick tour with reduced animations',
    'onboarding.features.palm_analysis': 'AI Palm Analysis',
    'onboarding.features.palm_analysis_desc': 'Precise palm feature identification with personalized readings',
    'onboarding.features.image_filters': 'Professional Image Filters',
    'onboarding.features.image_filters_desc': 'Multiple filter options to optimize photo quality',
    'onboarding.features.batch_processing': 'Batch Processing',
    'onboarding.features.batch_processing_desc': 'Process multiple photos at once for efficiency',
    'onboarding.features.themes': 'Theme Switching',
    'onboarding.features.themes_desc': 'Switch freely between light and dark modes',
    'onboarding.features.analytics': 'Usage Analytics',
    'onboarding.features.analytics_desc': 'Detailed usage statistics and insights analysis',
    'onboarding.features.social_sharing': 'Social Sharing',
    'onboarding.features.social_sharing_desc': 'Easily share results to major social platforms',
    'onboarding.steps.welcome.title': 'Welcome to AI Palm Reading',
    'onboarding.steps.welcome.description': 'Explore the perfect fusion of ancient wisdom and modern technology in your palmistry journey.',
    'onboarding.steps.theme-intro.title': 'Choose Your Perfect Theme',
    'onboarding.steps.theme-intro.description': 'Switch between light and dark modes, or let the app automatically follow your system preferences.',
    'onboarding.steps.upload-photo.title': 'Upload Your Hand Photo',
    'onboarding.steps.upload-photo.description': 'Take a clear photo of your palm or select from your gallery. Good lighting ensures better analysis results.',
    'onboarding.steps.image-filters.title': 'Enhance Your Image',
    'onboarding.steps.image-filters.description': 'Use professional filters to improve image quality. Try presets or adjust manually for the best results.',
    'onboarding.steps.palm-analysis.title': 'Get Your Reading',
    'onboarding.steps.palm-analysis.description': 'Our AI analyzes your palm lines and provides deep insights about emotion, intelligence, career, and vitality.',
    'onboarding.steps.batch-processing.title': 'Process Multiple Images',
    'onboarding.steps.batch-processing.description': 'Use batch processing to analyze several hand photos at once with consistent filter settings.',
    'onboarding.steps.social-sharing.title': 'Share Your Results',
    'onboarding.steps.social-sharing.description': 'Share your palm reading results on social media or download them for later reference.',
    'onboarding.steps.analytics-dashboard.title': 'Track Your Journey',
    'onboarding.steps.analytics-dashboard.description': 'Click the logo 5 times to access detailed analytics and see your usage patterns and insights.'
  }
}

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      currentLanguage: 'zh',
      
      setLanguage: (language: Language) => {
        set({ currentLanguage: language })
        // Update document language
        document.documentElement.lang = language
        // Update document title
        const title = translations[language]['app.title']
        document.title = title
      },
      
      t: (key: string) => {
        const { currentLanguage } = get()
        return (translations[currentLanguage] as Record<string, string>)[key] || key
      }
    }),
    {
      name: 'language-store'
    }
  )
)